/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workflow Schema */
        get: operations["workflow_schema_schema_workflow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/workflow-v0.3": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workflow Schema V0 3 */
        get: operations["workflow_schema_v0_3_schema_workflow_v0_3_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/resident-instance-v0.3": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resident Instance Schema V0 3 */
        get: operations["resident_instance_schema_v0_3_schema_resident_instance_v0_3_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/node-registry-v0.3": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Node Registry V0 3 */
        get: operations["node_registry_v0_3_schema_node_registry_v0_3_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_templates_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/persona-builder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Persona Builder */
        post: operations["create_persona_builder_templates_persona_builder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate */
        post: operations["validate_workflow_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Audit */
        post: operations["audit_workflow_audit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow/mock-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mock Run */
        post: operations["mock_run_workflow_mock_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow/export-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Preview */
        post: operations["export_preview_workflow_export_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resident/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compile Resident */
        post: operations["compile_resident_resident_compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resident/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Audit */
        post: operations["audit_resident_audit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resident/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_resident_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Artifact */
        Artifact: {
            /** Artifact Id */
            artifact_id: string;
            /** Node Id */
            node_id: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Preview */
            preview?: {
                [key: string]: unknown;
            };
        };
        /** AuditFinding */
        AuditFinding: {
            status: components["schemas"]["AuditStatus"];
            level: components["schemas"]["AuditLevel"];
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Path */
            path: string;
        };
        /**
         * AuditLevel
         * @enum {string}
         */
        AuditLevel: "node" | "module" | "layer" | "resident";
        /** AuditReportV03 */
        AuditReportV03: {
            /**
             * Schema Version
             * @default 0.3.0
             * @constant
             */
            schema_version: "0.3.0";
            /** @default PASS */
            status: components["schemas"]["AuditStatus"];
            /** Findings */
            findings?: components["schemas"]["AuditFinding"][];
        };
        /** AuditResponse */
        AuditResponse: {
            audit: components["schemas"]["AuditReportV03"];
        };
        /**
         * AuditStatus
         * @enum {string}
         */
        AuditStatus: "PASS" | "WARNING" | "FAIL";
        /** EdgeV03 */
        EdgeV03: {
            /** Id */
            id: string;
            /** Source Node Id */
            source_node_id: string;
            /** Source Output */
            source_output: string;
            /** Target Node Id */
            target_node_id: string;
            /** Target Input */
            target_input: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** ExportPreview */
        ExportPreview: {
            /**
             * Schema Version
             * @default 0.3.0
             */
            schema_version: string;
            /**
             * Export Kind
             * @enum {string}
             */
            export_kind: "workflow_json" | "persona";
            /** Content */
            content?: {
                [key: string]: unknown;
            };
            /** Warnings */
            warnings?: string[];
        };
        /** ExportPreviewRequest */
        ExportPreviewRequest: {
            /** Workflow */
            workflow: unknown;
            /**
             * Export Kind
             * @enum {string}
             */
            export_kind: "workflow_json" | "persona" | "resident";
        };
        /** ExportPreviewResponse */
        ExportPreviewResponse: {
            preview: components["schemas"]["ExportPreview"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /**
             * Schema Version
             * @default 0.3.0
             */
            schema_version: string;
        };
        /** LayerV03 */
        LayerV03: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Module Ids */
            module_ids?: string[];
            /** Node Ids */
            node_ids?: string[];
            /** Output Schema */
            output_schema?: components["schemas"]["OutputSchemaField"][];
            /** Outputs */
            outputs?: {
                [key: string]: unknown;
            };
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** MockRunResponse */
        MockRunResponse: {
            run: components["schemas"]["RunResult"];
        };
        /** ModuleV03 */
        ModuleV03: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Layer Id */
            layer_id?: string | null;
            /** Node Ids */
            node_ids?: string[];
            /** Output Schema */
            output_schema?: components["schemas"]["OutputSchemaField"][];
            /** Outputs */
            outputs?: {
                [key: string]: unknown;
            };
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** NodeInputField */
        NodeInputField: {
            /** Key */
            key: string;
            type: components["schemas"]["NodeInputType"];
            /** Label */
            label: string;
            /**
             * Required
             * @default false
             */
            required: boolean;
            /** Default */
            default?: unknown | null;
            /** Placeholder */
            placeholder?: string | null;
            /** Options */
            options?: components["schemas"]["NodeInputOption"][];
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /** Step */
            step?: number | null;
            /** Accept */
            accept?: string[] | null;
            /**
             * Multiple
             * @default false
             */
            multiple: boolean;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** NodeInputOption */
        NodeInputOption: {
            /** Value */
            value: string;
            /** Label */
            label: string;
        };
        /**
         * NodeInputType
         * @enum {string}
         */
        NodeInputType: "text" | "textarea" | "number" | "select" | "multi_select" | "slider" | "boolean" | "color" | "json" | "tags" | "key_value" | "file";
        /** NodeRunResult */
        NodeRunResult: {
            /** Node Id */
            node_id: string;
            status: components["schemas"]["RunStatus"];
            /** Output */
            output?: {
                [key: string]: unknown;
            };
            /** Logs */
            logs?: components["schemas"]["RunLog"][];
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
        };
        /**
         * NodeStatus
         * @enum {string}
         */
        NodeStatus: "READY" | "MOCK" | "DISABLED";
        /** NodeUiState */
        NodeUiState: {
            /**
             * Collapsed
             * @default false
             */
            collapsed: boolean;
            /** Position */
            position?: {
                [key: string]: number;
            };
            /** Size */
            size?: {
                [key: string]: number;
            };
            /** Color */
            color?: string | null;
            /**
             * Selected
             * @default false
             */
            selected: boolean;
        };
        /** NodeV03 */
        NodeV03: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Label */
            label: string;
            /** Category */
            category: string;
            status: components["schemas"]["NodeStatus"];
            /** Input Schema */
            input_schema?: components["schemas"]["NodeInputField"][];
            /** Inputs */
            inputs?: {
                [key: string]: unknown;
            };
            /** Output Schema */
            output_schema?: components["schemas"]["OutputSchemaField"][];
            /** Outputs */
            outputs?: {
                [key: string]: unknown;
            };
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            ui?: components["schemas"]["NodeUiState"];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * OutputDtoV03
         * @description Final JSON output DTO. No UI state or runtime context is allowed here.
         */
        OutputDtoV03: {
            /**
             * Schema Version
             * @default 0.3.0
             * @constant
             */
            schema_version: "0.3.0";
            /** Kind */
            kind: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** OutputSchemaField */
        OutputSchemaField: {
            /** Key */
            key: string;
            /**
             * Type
             * @enum {string}
             */
            type: "string" | "number" | "boolean" | "object" | "array" | "null";
            /**
             * Required
             * @default false
             */
            required: boolean;
            /** Description */
            description?: string | null;
        };
        /** PersonaBuilderRequest */
        PersonaBuilderRequest: {
            /** Name */
            name?: string | null;
            /** Ui Language */
            ui_language?: string | null;
        };
        /** PersonaBuilderResponse */
        PersonaBuilderResponse: {
            workflow: components["schemas"]["WorkflowV03"];
        };
        /** ResidentAuditRequest */
        ResidentAuditRequest: {
            resident_instance: components["schemas"]["ResidentInstanceV03"];
        };
        /** ResidentAuditResponse */
        ResidentAuditResponse: {
            audit: components["schemas"]["AuditReportV03"];
        };
        /** ResidentAvatar */
        ResidentAvatar: {
            /**
             * Preset
             * @default mock_avatar
             */
            preset: string;
            /**
             * Color
             * @default #7aa2f7
             */
            color: string;
            /**
             * Density
             * @default 0.6
             */
            density: number;
            /**
             * Motion
             * @default idle
             */
            motion: string;
            /**
             * Mock
             * @default true
             */
            mock: boolean;
        };
        /** ResidentCompileRequestV03 */
        ResidentCompileRequestV03: {
            /** Workflow */
            workflow?: unknown | null;
            resident_instance?: components["schemas"]["ResidentInstanceV03"] | null;
            ui_state?: components["schemas"]["UiStateV03"] | null;
            runtime_context?: components["schemas"]["RuntimeContextV03"] | null;
        };
        /** ResidentCompileResponseV03 */
        ResidentCompileResponseV03: {
            /**
             * Schema Version
             * @default 0.3.0
             * @constant
             */
            schema_version: "0.3.0";
            resident_instance: components["schemas"]["ResidentInstanceV03"];
            audit: components["schemas"]["AuditReportV03"];
        };
        /** ResidentDialogue */
        ResidentDialogue: {
            /**
             * Tone
             * @default warm
             */
            tone: string;
            /**
             * Formality
             * @default casual
             */
            formality: string;
            /**
             * Sample
             * @default
             */
            sample: string;
        };
        /** ResidentIdentity */
        ResidentIdentity: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Role
             * @default digital_resident
             */
            role: string;
            /** Description */
            description?: string | null;
            /**
             * Disclosure
             * @default AI-generated digital resident; synthetic persona.
             */
            disclosure: string;
        };
        /** ResidentInstanceV03 */
        ResidentInstanceV03: {
            identity?: components["schemas"]["ResidentIdentity"];
            personality?: components["schemas"]["ResidentPersonality"];
            dialogue?: components["schemas"]["ResidentDialogue"];
            voice_profile?: components["schemas"]["ResidentVoiceProfile"];
            avatar?: components["schemas"]["ResidentAvatar"];
            metadata?: components["schemas"]["ResidentMetadata"];
        };
        /** ResidentMetadata */
        ResidentMetadata: {
            /**
             * Schema Version
             * @default 0.3.0
             * @constant
             */
            schema_version: "0.3.0";
            /**
             * Mock
             * @default true
             */
            mock: boolean;
            /** Tags */
            tags?: string[];
            /** Notes */
            notes?: string | null;
        };
        /** ResidentPersonality */
        ResidentPersonality: {
            /** Traits */
            traits?: string[];
            /**
             * Speaking Style
             * @default
             */
            speaking_style: string;
            /** Boundaries */
            boundaries?: string[];
        };
        /** ResidentPreviewRequestV03 */
        ResidentPreviewRequestV03: {
            resident_instance: components["schemas"]["ResidentInstanceV03"];
            ui_state?: components["schemas"]["UiStateV03"] | null;
        };
        /** ResidentPreviewResponseV03 */
        ResidentPreviewResponseV03: {
            /**
             * Schema Version
             * @default 0.3.0
             * @constant
             */
            schema_version: "0.3.0";
            preview: components["schemas"]["OutputDtoV03"];
            audit: components["schemas"]["AuditReportV03"];
        };
        /** ResidentVoiceProfile */
        ResidentVoiceProfile: {
            /**
             * Voice Id
             * @default mock_voice
             */
            voice_id: string;
            /**
             * Pitch
             * @default medium
             */
            pitch: string;
            /**
             * Speed
             * @default 1
             */
            speed: number;
            /**
             * Timbre
             * @default neutral
             */
            timbre: string;
            /**
             * Mock
             * @default true
             */
            mock: boolean;
        };
        /** RunLog */
        RunLog: {
            /**
             * Ts
             * Format: date-time
             */
            ts?: string;
            /**
             * Level
             * @default info
             * @enum {string}
             */
            level: "info" | "warn" | "error";
            /** Message */
            message: string;
        };
        /** RunResult */
        RunResult: {
            /**
             * Schema Version
             * @default 0.3.0
             */
            schema_version: string;
            /** Workflow Id */
            workflow_id: string;
            status: components["schemas"]["RunStatus"];
            /** Order */
            order?: string[];
            /** Node Results */
            node_results?: components["schemas"]["NodeRunResult"][];
            /** Artifacts */
            artifacts?: components["schemas"]["Artifact"][];
            /**
             * Started At
             * Format: date-time
             */
            started_at?: string;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at?: string;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "pending" | "running" | "success" | "warning" | "error" | "skipped";
        /**
         * RuntimeContextV03
         * @description Execution-only context. Contract type only; no endpoint executes it.
         */
        RuntimeContextV03: {
            /** Run Id */
            run_id: string;
            /** Workflow Id */
            workflow_id?: string | null;
            /** Current Node Id */
            current_node_id?: string | null;
            /** Variables */
            variables?: {
                [key: string]: unknown;
            };
        };
        /** TemplateDefinition */
        TemplateDefinition: {
            /**
             * Schema Version
             * @default 0.3.0
             */
            schema_version: string;
            /** Template Type */
            template_type: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Builder */
            builder: string;
        };
        /** TemplatesListResponse */
        TemplatesListResponse: {
            /** Templates */
            templates: components["schemas"]["TemplateDefinition"][];
        };
        /**
         * UiStateV03
         * @description Frontend-only state. It must never be embedded in output DTOs.
         */
        UiStateV03: {
            /** Selected Node Id */
            selected_node_id?: string | null;
            /** Viewport */
            viewport?: {
                [key: string]: number;
            };
            /** Panels */
            panels?: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkflowMetadataV03 */
        WorkflowMetadataV03: {
            /** Description */
            description?: string | null;
            /** Author */
            author?: string | null;
            /** Tags */
            tags?: string[];
            /** Ui Language */
            ui_language?: ("zh" | "en") | null;
            /**
             * Mock
             * @default true
             */
            mock: boolean;
        };
        /** WorkflowPayloadRequest */
        WorkflowPayloadRequest: {
            /** Workflow */
            workflow: unknown;
        };
        /** WorkflowV03 */
        WorkflowV03: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Schema Version
             * @default 0.3.0
             * @constant
             */
            schema_version: "0.3.0";
            /** Layers */
            layers?: components["schemas"]["LayerV03"][];
            /** Modules */
            modules?: components["schemas"]["ModuleV03"][];
            /** Nodes */
            nodes?: components["schemas"]["NodeV03"][];
            /** Edges */
            edges?: components["schemas"]["EdgeV03"][];
            metadata?: components["schemas"]["WorkflowMetadataV03"];
        };
        /** WorkflowValidationResponseV03 */
        WorkflowValidationResponseV03: {
            /**
             * Schema Version
             * @default 0.3.0
             * @constant
             */
            schema_version: "0.3.0";
            /** Valid */
            valid: boolean;
            audit: components["schemas"]["AuditReportV03"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    workflow_schema_schema_workflow_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    workflow_schema_v0_3_schema_workflow_v0_3_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    resident_instance_schema_v0_3_schema_resident_instance_v0_3_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    node_registry_v0_3_schema_node_registry_v0_3_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_templates_templates_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplatesListResponse"];
                };
            };
        };
    };
    create_persona_builder_templates_persona_builder_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonaBuilderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaBuilderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_workflow_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowPayloadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowValidationResponseV03"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_workflow_audit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowPayloadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mock_run_workflow_mock_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowPayloadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_preview_workflow_export_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compile_resident_resident_compile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResidentCompileRequestV03"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResidentCompileResponseV03"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_resident_audit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResidentAuditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResidentAuditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_resident_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResidentPreviewRequestV03"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResidentPreviewResponseV03"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
