/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workflow Schema */
        get: operations["workflow_schema_schema_workflow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_templates_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/persona-builder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Persona Builder */
        post: operations["create_persona_builder_templates_persona_builder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate */
        post: operations["validate_workflow_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow/mock-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mock Run */
        post: operations["mock_run_workflow_mock_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow/export-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Preview */
        post: operations["export_preview_workflow_export_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Artifact */
        Artifact: {
            /** Artifact Id */
            artifact_id: string;
            /** Node Id */
            node_id: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Preview */
            preview?: {
                [key: string]: unknown;
            };
        };
        /** ExportPreview */
        ExportPreview: {
            /**
             * Schema Version
             * @default 0.2.0
             */
            schema_version: string;
            /**
             * Export Kind
             * @enum {string}
             */
            export_kind: "workflow_json" | "persona";
            /** Content */
            content?: {
                [key: string]: unknown;
            };
            /** Warnings */
            warnings?: string[];
        };
        /** ExportPreviewRequest */
        ExportPreviewRequest: {
            workflow: components["schemas"]["Workflow"];
            /**
             * Export Kind
             * @enum {string}
             */
            export_kind: "workflow_json" | "persona";
        };
        /** ExportPreviewResponse */
        ExportPreviewResponse: {
            preview: components["schemas"]["ExportPreview"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /**
             * Schema Version
             * @default 0.2.0
             */
            schema_version: string;
        };
        /**
         * LockLevel
         * @enum {string}
         */
        LockLevel: "editable" | "review_required" | "locked" | "system_locked" | "mixed";
        /** MockRunRequest */
        MockRunRequest: {
            workflow: components["schemas"]["Workflow"];
        };
        /** MockRunResponse */
        MockRunResponse: {
            run: components["schemas"]["RunResult"];
        };
        /**
         * NodeCategory
         * @enum {string}
         */
        NodeCategory: "source" | "processing" | "ai" | "control" | "container" | "sink";
        /** NodeRunResult */
        NodeRunResult: {
            /** Node Id */
            node_id: string;
            status: components["schemas"]["RunStatus"];
            /** Output */
            output?: {
                [key: string]: unknown;
            };
            /** Logs */
            logs?: components["schemas"]["RunLog"][];
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
        };
        /**
         * NodeType
         * @enum {string}
         */
        NodeType: "input" | "transform" | "model" | "agent" | "review" | "layer_container" | "output" | "export";
        /** PersonaBuilderRequest */
        PersonaBuilderRequest: {
            /** Name */
            name?: string | null;
            /** Ui Language */
            ui_language?: string | null;
        };
        /** PersonaBuilderResponse */
        PersonaBuilderResponse: {
            workflow: components["schemas"]["Workflow"];
        };
        /** Port */
        Port: {
            /** Port Id */
            port_id: string;
            /** Name */
            name: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "in" | "out";
        };
        /** Ports */
        Ports: {
            /** Inputs */
            inputs?: components["schemas"]["Port"][];
            /** Outputs */
            outputs?: components["schemas"]["Port"][];
        };
        /** Position */
        Position: {
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
        };
        /**
         * ReviewScope
         * @enum {string}
         */
        ReviewScope: "node" | "layer" | "package";
        /**
         * ReviewStatus
         * @enum {string}
         */
        ReviewStatus: "pending" | "passed" | "warning" | "failed";
        /** RunLog */
        RunLog: {
            /**
             * Ts
             * Format: date-time
             */
            ts?: string;
            /**
             * Level
             * @default info
             * @enum {string}
             */
            level: "info" | "warn" | "error";
            /** Message */
            message: string;
        };
        /** RunResult */
        RunResult: {
            /**
             * Schema Version
             * @default 0.2.0
             */
            schema_version: string;
            /** Workflow Id */
            workflow_id: string;
            status: components["schemas"]["RunStatus"];
            /** Order */
            order?: string[];
            /** Node Results */
            node_results?: components["schemas"]["NodeRunResult"][];
            /** Artifacts */
            artifacts?: components["schemas"]["Artifact"][];
            /**
             * Started At
             * Format: date-time
             */
            started_at?: string;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at?: string;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "pending" | "running" | "success" | "warning" | "error" | "skipped";
        /** TemplateDefinition */
        TemplateDefinition: {
            /**
             * Schema Version
             * @default 0.2.0
             */
            schema_version: string;
            /** Template Type */
            template_type: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Builder */
            builder: string;
        };
        /** TemplatesListResponse */
        TemplatesListResponse: {
            /** Templates */
            templates: components["schemas"]["TemplateDefinition"][];
        };
        /** ValidateRequest */
        ValidateRequest: {
            workflow: components["schemas"]["Workflow"];
        };
        /** ValidateResponse */
        ValidateResponse: {
            package: components["schemas"]["ValidationReview"];
            /** Layers */
            layers: components["schemas"]["ValidationReview"][];
            /** Nodes */
            nodes: components["schemas"]["ValidationReview"][];
        };
        /** ValidationCheck */
        ValidationCheck: {
            /** Rule */
            rule: string;
            /**
             * Level
             * @enum {string}
             */
            level: "error" | "warning";
            /** Target Id */
            target_id?: string | null;
            /** Message */
            message: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationReview */
        ValidationReview: {
            /**
             * Schema Version
             * @default 0.2.0
             */
            schema_version: string;
            scope: components["schemas"]["ReviewScope"];
            status: components["schemas"]["ReviewStatus"];
            /** Checks */
            checks?: components["schemas"]["ValidationCheck"][];
            /**
             * Checked At
             * Format: date-time
             */
            checked_at?: string;
        };
        /** Viewport */
        Viewport: {
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
            /**
             * Zoom
             * @default 1
             */
            zoom: number;
        };
        /** Workflow */
        Workflow: {
            /**
             * Schema Version
             * @default 0.2.0
             */
            schema_version: string;
            /** Workflow Id */
            workflow_id?: string;
            /** Name */
            name: string;
            /**
             * Version
             * @default 1.0.0
             */
            version: string;
            /**
             * Template Type
             * @default blank
             */
            template_type: string;
            /** Content Locale */
            content_locale?: string | null;
            /** Nodes */
            nodes?: components["schemas"]["WorkflowNode"][];
            /** Edges */
            edges?: components["schemas"]["WorkflowEdge"][];
            viewport?: components["schemas"]["Viewport"] | null;
            metadata?: components["schemas"]["WorkflowMetadata"];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /** WorkflowEdge */
        WorkflowEdge: {
            /** Edge Id */
            edge_id: string;
            /** Source */
            source: string;
            /** Source Port */
            source_port: string;
            /** Target */
            target: string;
            /** Target Port */
            target_port: string;
        };
        /** WorkflowMetadata */
        WorkflowMetadata: {
            /** Description */
            description?: string | null;
            /** Author */
            author?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Ui Language */
            ui_language?: string | null;
        };
        /** WorkflowNode */
        WorkflowNode: {
            /** Node Id */
            node_id: string;
            type: components["schemas"]["NodeType"];
            category: components["schemas"]["NodeCategory"];
            /** Title Key */
            title_key: string;
            /** Title Fallback */
            title_fallback: string;
            position?: components["schemas"]["Position"];
            lock_level: components["schemas"]["LockLevel"];
            /** Locale */
            locale?: string | null;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            ports?: components["schemas"]["Ports"];
            validation?: components["schemas"]["ValidationReview"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    workflow_schema_schema_workflow_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_templates_templates_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplatesListResponse"];
                };
            };
        };
    };
    create_persona_builder_templates_persona_builder_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonaBuilderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaBuilderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_workflow_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mock_run_workflow_mock_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MockRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_preview_workflow_export_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
